// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://orxrkdryngbmkqbdvzcw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9yeHJrZHJ5bmdibWtxYmR2emN3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5NTQxMjUsImV4cCI6MjA2MjUzMDEyNX0.DGWyycDxy0dy7-78fPZx5VjtBpB0HnPnTDNkEolIhn0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);